//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHSGV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        public string MaHS { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GT { get; set; }
        public string DiaChi { get; set; }
        public string TenLop { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
    }
}
